### PR TITLE
Add menu support

### PR DESCRIPTION
**Pull request by tsurai**
This pull request adds menu support as an optional feature to the crate.

I meant to add this feature for a while but couldn't because it wasn't possible to allocate a C string in Rust and transfer ownership to C without leaking. This [feature](https://github.com/rust-lang/rust/pull/25777) has been finally added to rust recently.

It has only been added to nightly and NOT yet to rust stable.

### CODE REVIEW

**Comment by jeaye** [comment]
1. It'd be great to get an example added, showing how this can be used
2. I'm interested in what other ncurses-rs users have to say about the addition

Thanks for this PR. I'm looking forward to seeing it merged.

**Comment by tsurai** [comment]
1. I've added an example very similar to the ones in the official [documentation](http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/menus.html). The README says that the difficulty of the example increases with the number which is why I'm not sure where to put it but you can do it as you please.

2. I can't speak for the rest of the ncurses-rs users but personally I think that it just makes sense to add the menu library functions because it's a part of ncurses and gets shipped with it. Just like the panel library which has already been added.
But other users may have a different opinion

**Comment by jeaye** [comment]
Will you add this as the new `5` in the README and shift the existing on to `6`?

I certainly think this is a good change, but the only last obstacle is how much we want support for Rust stable, especially considering that there is a stable Rust now.

**Comment by tsurai** [comment]
I tried to get it to work with Rust stable for days and had to find out that it's unfortunately not possible right now.

All menu library functions are behind a feature gate meaning that ncurses-rs as it is right now still compiles with Rust stable and won't break for anyone. It's like an opt-in extra feature for those using rust nightly.

But if you really don't want any unstable code in ncurses-rs you may also wait until the CString reform lands in Rust stable.

**Comment by jeaye** [comment]
It's gated off and compiles with stable, and I think it's a great addition, so I've merged it in. Thanks so much for your wok on this.

**Pull request merged**
